### ISSUE TITLE
Cannot install via yay 

### ISSUE THREAD

**Issue by Darkpaladi** [margual56/radio-cli#1] opened 2022-03-28 14:24 UTC
Output:
```
yay -S radio-cli-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  radio-cli-git-0.1.0-1

  1 radio-cli-git                            (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/0): radio-cli-git
  1 radio-cli-git                            (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: radio-cli-git
==> Making package: radio-cli-git 0.1.0-1 (Mon Mar 28 16:20:12 2022)
==> Retrieving sources...
  -> Updating radio-cli git repo...
Fetching origin
==> Validating source files with md5sums...
    radio-cli ... Skipped
==> Making package: radio-cli-git 0.1.0-1 (Mon Mar 28 16:20:14 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating radio-cli git repo...
Fetching origin
==> Validating source files with md5sums...
    radio-cli ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of radio-cli git repo...
Cloning into 'radio-cli'...
done.
==> Starting prepare()...
mkdir: cannot create directory ‘/radio-cli/’: Permission denied
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: radio-cli-git
```

There seems to be some permission issues in the "prepare()" function. I have tried executing `yay -S radio-cli-git` with sudo and I have rust installed.

**Comment by margual56** [comment] 2022-03-28 14:47
The problem seems to be the line that creates the config folder:
```bash
mkdir -p "${XDG_CONFIG_HOME}/radio-cli/"
```
This is because if `XDG_CONFIG_HOME` is not defined, it would try to create the folder on the root. 

@Darkpaladi Could you please tell me what is the output of `echo $XDG_CONFIG_HOME` in your system?

**Comment by Darkpaladi** [comment] 2022-03-29 09:11
Sure.
```
echo $XDG_CONFIG_HOME

```
It doesn't return anything.

**Comment by margual56** [comment] 2022-03-29 13:51
Then it is confirmed. I have pushed a fix to the AUR's PKGBUILD, it should work now. Could you check if it works for you?

**Comment by margual56** [comment] 2022-04-18 10:19
Closing because `radio-cli-git` has been replaced with `radio-cli-bin`

**Closed by margual56** 2022-04-18 10:19 UTC
Labels: bug, AUR
